### ISSUE TITLE
Unable to power on Beovision 11

### ISSUE THREAD

**Issue by spacecakes** [giachello/beoplay#17]
Latest version of component and Home Assistant. I can power of the TV but it does not power on again. Anything I can change to make this work?

**Comment by rob-da** [comment]
You may have power saving enabled on the bv11.

**Comment by spacecakes** [comment]
I don't. I can power it on and off with Homebridge and the BeoPlay plugin, but not HA unfortunately.

**Comment by giachello** [comment]
I think the BeoVision requires you to select a source to power it on. A the generic 'power on' won't work.
