### ISSUE TITLE
discovery_info.get('name') warning

### ISSUE THREAD

**Issue by KimCarlsen** [giachello/beoplay#19]
Get this warning in the log on 2022.5
Detected integration that accessed discovery_info.get('name') instead of discovery_info.name; this will fail in version 2022.6. Please report issue to the custom component author for beoplay using this method at custom_components/beoplay/config_flow.py, line 100: if not discovery_info.get("name") or not discovery_info["name"].startswith(

**Comment by giachello** [comment]
I fixed this in the latest version of the code on github. Please re-install.

**Comment by KimCarlsen** [comment]
Thanks. I had the latest release, not the latest code from the repo.
