### ISSUE TITLE
not unique ID's

### ISSUE THREAD

**Issue by KimCarlsen** [giachello/beoplay#21]
hi.
Getting this in the HA logs.:
Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:652
Integration: Media player (documentation, issues)
First occurred: August 22, 2022 at 06:21:13 (1 occurrences)
Last logged: August 22, 2022 at 06:21:13

Platform beoplay does not generate unique IDs. ID already exists - ignoring media_player.beoplay

**Comment by giachello** [comment]
I fixed this, let me know if this works now.

**Comment by KimCarlsen** [comment]
Thanks. just installed and readded all devices. Errors gone
