### ISSUE TITLE
Light and Control functions

### ISSUE THREAD

**Issue by TrammRasmusen** [giachello/beoplay#27]
Hi Giachello

It would be nice if this integration could handle the Light and Control/FuncXX_KeyPress, from the Beoremote One.

So it's possible to name the different functions on the remote.

Thank you for this integration in general - it works flawlessly :)

**Comment by giachello** [comment]
Unfortunately, I don't think the BeoPlay protocol API actually can do that. The BeoOne keys are not sent through the notifications channel AFAIR. For that functionality you should purchase a MasterLink Gateway or BeoLink Gateway and use my other https://github.com/giachello/mlgw integration.

Try doing this: open a browser and type this URL
http://192.168.1.83:8080/BeoNotify/Notifications
(change the IP address 192.168.1.83 to the IP of your TV)

If you see activity when you press those keys, then let me know.

**Comment by TrammRasmusen** [comment]
I've tried it with my Beovision Avant - no results. But then I tried on a Beoplay M3 and it works and the command goes through. If you could include this in your integration, that would be absolutely brilliant. Thank you for your time.

Sincerely
Christian 



{"notification":{"timestamp":"2023-02-12T18:09:38.470695","type":"SOURCE","kind":"source","data":{}}}

{"notification":{"timestamp":"2023-02-12T18:09:38.471967","type":"NOW_PLAYING_ENDED","kind":"playing","data":{}}}

{"notification":{"timestamp":"2023-02-12T18:09:38.472131","type":"PROGRESS_INFORMATION","kind":"playing","data":{"state":"stop"}}}

{"notification":{"timestamp":"2023-02-12T18:09:38.472339","type":"VOLUME","kind":"renderer","data":{"speaker":{"level":39,"muted":false,"range":{"minimum":0,"maximum":51}}}}}

{"notification":{"timestamp":"2023-02-12T18:09:38.472807","type":"SOFTWARE_UPDATE_STATE","kind":"device","data":{"state":"idle"}}}





{"notification":{"id":1231,"timestamp":"2023-02-12T18:09:49.851828","type":"COMMAND","kind":"device","data":{"category":"Light","key":"Function1","event":"KeyPress","toBeReleased":true}}}

{"notification":{"id":1232,"timestamp":"2023-02-12T18:09:49.934494","type":"COMMAND","kind":"device","data":{"category":"Light","key":"Function1","event":"KeyRelease"}}}

**Comment by giachello** [comment]
Soo.. do you see them come through in the Developer Tools -> Events -> "beoplay_notification" -> Start Listening? See here:
![image](https://user-images.githubusercontent.com/60585229/218329950-a3a5b24a-9ce5-4a91-84f0-f9f20e4498f9.png)

**Comment by TrammRasmusen** [comment]
Perfect it works - I did not know of the "beoplay_notification".
Maybe you could write it on the front page, I think many people would use it if they knew about it :)

Thank you :) 




event_type: beoplay_notification
data:
  id: 2867
  timestamp: "2023-02-12T21:00:09.822833"
  type: COMMAND
  kind: device
  data:
    category: Light
    key: Function1
    event: KeyPress
    toBeReleased: true
  entity_id: media_player.28712703
origin: LOCAL
time_fired: "2023-02-12T21:00:09.826417+00:00"
context:
  id: 01GS3PV5Q2NCV9GJZEP7JK0RX0
  parent_id: null
  user_id: null

**Comment by giachello** [comment]
It actually is already there :-) ... will move it up.

**Comment by nigels0** [comment]
I’m using a Beosystem 4 and while I get some events in HA, the Light command isn’t one of them
