### ISSUE TITLE
Next and Previous not working

### ISSUE THREAD

**Issue by saltinesurfer** [giachello/beoplay#29]
Hi Giovanni,

Thank you for all the time and effort you put into this great integration! I've noticed that the next & previous controls are not working for the Beoplay A9 mk4 and M5. However they work for the BV11. This is using the mini media player. The service call to media_next_track doesn't do anything either. Play/stop/power/join however do work.

Many thanks!

Rob.

**Comment by giachello** [comment]
Try using the new remote commands in 2023.4.1 and see if that works for you. Let me know!

**Comment by saltinesurfer** [comment]
> Try using the new remote commands in 2023.4.1 and see if that works for you. Let me know!

Sorry for the mega late reply! I've just tested the remote service commands and they work thanks. However the mini-media-player component buttons call the media_player.media_next_track / previous commands which aren't working. Hoping it's an easy fix. 

Issue #34 looks to be a duplicate of this. 

Many thanks,

Rob.

**Comment by giachello** [comment]
Hi, so the strange thing is that these are the right commands for my Beolink Converter and BeoVision Avant. Not sure that if I make the change in #34 it will not break something else.

**Comment by giachello** [comment]
Same as #34
