### ISSUE TITLE
Choosing radio station 

### ISSUE THREAD

**Issue by nigels0** [giachello/beoplay#33]
Is there a way to choose a specific radio station from the favourites list?

**Comment by giachello** [comment]
if it has a number 1-9, then that would work using the "remote" function. 

Otherwise , there may be a way using the HTTP API ( https://documenter.getpostman.com/view/1053298/T1LTe4Lt ) but not sure how that works. If you figure out the HTTP API command, we can add it to the plugin.

**Comment by nigels0** [comment]
Hi,

I didn’t know you could use numbers with the remote command - any attempt I made using the developer tools seemed to fail as it isn’t listed as one of the commands. Could you give me an example of how it would work please?

**Comment by giachello** [comment]
You are right, I checked and  I don't think there is a way to select channels directly using the plugin.
