### ISSUE TITLE
allstandby error

### ISSUE THREAD

**Issue by MichaelRV82** [giachello/beoplay#35]
Hi,

After updating HA to latest release I get this error:

![IMG_3645](https://github.com/giachello/beoplay/assets/92013548/0f3d3580-7dcd-4f6a-a083-90cfb3a6e2d5)

Any Ideas?

**Comment by giachello** [comment]
Hi! Are you sure you are using this integration ? There is no service with that name exposed from here. See the service.yaml file.

-g
