### ISSUE TITLE
Media Player entity is Missing after Update to v2024

### ISSUE THREAD

**Issue by FlorianGrefing** [giachello/beoplay#37]
after updating from v2023.4.2 to v2024.3.2 the Media Player entity is missing while power on/off is still available.
Restore to v2023.4.2 solves the issue

testet with Beovision Avant 55 Type 8641

Home Assistant Installation 
Core 2024.3.1 and 2024.3.0 testet
Supervisor 2024.03.0
Operating System 12.1

Generic x86-64

**Comment by giachello** [comment]
Did you try uninstalling and reinstalling?
Also is the entity just a different name now? Can you check the Entities list and see if you find the device under a different name?

**Comment by FlorianGrefing** [comment]
No different names or entities

deleting / reinstall the device worked fine

Thumbs up
