### ISSUE TITLE
Python warning message

### ISSUE THREAD

**Issue by mbolo01** [giachello/beoplay#4]
Hi there. Please note the following message:

_/config/custom_components/beoplay/media_player.py:266: DeprecationWarning: The loop argument is deprecated since Python 3.8, and schedul
ed for removal in Python 3.10.                                                                                                          
  await asyncio.sleep(CHECK_TIMEOUT, loop=self._hass.loop)_

Kind regards.

**Comment by tirkarthi** [comment]
The loop parameter has been removed in Python 3.10 : https://bugs.python.org/issue42392

**Comment by giachello** [comment]
removed from code.
