### ISSUE TITLE
Beoplay M3 and M5 no longer available as media player

### ISSUE THREAD

**Issue by stef798** [giachello/beoplay#40]
Hi Giachello,
upfront, thanks for the amazing integration. Worked like a charme in the past!

I updated the beoplay integration. Now, my B&O M5 and M3 speaker are no longer available as media_player. Only as remote.
![image](https://github.com/user-attachments/assets/f61e4c55-3660-4f07-8cda-9b54228508b0)

I deleted the M3 and set it up again. This time it only showed up as remote.

Do you have any idea what happened?

Kind regards,
Stefan

**Comment by giachello** [comment]
Can you enable debugging, restart home assisstant and send me the logs? 
<img width="1126" alt="image" src="https://github.com/user-attachments/assets/430887d9-d64d-4eb6-b0f4-6d11a2e3efcb">

<img width="587" alt="image" src="https://github.com/user-attachments/assets/e3638ddc-c39d-42f0-8a05-40344f07ff9c">

**Comment by stef798** [comment]
Restart helped. It seems like it just took a while. Works perfectly now
