### ISSUE TITLE
Feature request: sound mode support

### ISSUE THREAD

**Issue by hugobloem** [giachello/beoplay#41]
Thank you very much for this integration. 

On the Postman page Sound Mode is noted as only being supported by TVs. However, on my Stage I can query and set the Sound Mode using [these commands](https://documenter.getpostman.com/view/1053298/T1LTe4Lt#32cddd98-2537-49e8-815c-39b7fb7e861c). I don't have other devices to test this with, so the Stage may be an anomaly. 

If it is more widely supported, is there scope to support this in this integration? I could draft a PR to add the functionality if you want.

**Comment by giachello** [comment]
Interesting. Do submit a PR. But make sure you build the actual logic to talk with the Stage in pybeoplay library, not in this plugin which is just the interface to Home Assistant. I won't accept a PR that talks directly to the device from beoplay.

**Comment by hugobloem** [comment]
I've submitted a PR to pybeoplay, once that is merged I'll work on getting it in here. https://github.com/giachello/pybeoplay/pull/5

**Comment by giachello** [comment]
Cool! I merged it. Give me a couple days to rebuild the pypi package. I'm not on my dev machine now.

**Comment by hugobloem** [comment]
Yes, I can confirm it works. Thank you for merging this!

**Comment by giachello** [comment]
Solved in v2024.12.2
