### ISSUE TITLE
Beolink Converter ML/NL behaviour

### ISSUE THREAD

**Issue by roliestermann** [giachello/beoplay#5]
Dear Giovanni
I'm using both of your integrations, beoplay as well as mlgw with home-assistant. Thank you very much for all your time you spent in developing this, really appreciated.
I was setting both up and playing around with my setup at home. Most of the things are working out of the box, or if I faced issues like with the virtual button to send to the blgw, there is already a fix which is working.
I'm using beoplay integration to control my Beo11-55, as well as my Converter ML/NL, which I used to 'wireless' interconnect my Beo10 in another room. So I setup the NL/ML Converter as ML Audio-Master. Discovery works, and the Converter with it's sources will be recognised. I can choose a source of Radio and the Beo10 turns on and plays Radio. The only thing, the status in the mini-player will not be updated.  When I check the ML/NL Converter, the state is: nowPlaying= & nowPlayingDetails=type: Legacy; track number: 9 & online=Yes & sourceName=RADIO & sourceUniqueId=RADIO:1790.1179011.23026358@products.bang-olufsen.com & state=Play & volume=50

So if I change now the source from RADIO to f.e. CD with me Beo-Remote, the state of the mini-media player gets updated automatically.

As long as this state is not updated, I'm not able to turn off the Beo10 with the mini-player app. As soon as the state is updated, I can turn off with app. Do you perhaps have an idea? 

I'm not sure, if my explanation is clear enough. If so, please apologise.

Have a great start into the new day, and stay healthy.
Best
Roli

**Comment by giachello** [comment]
I refactored status update logic. Will close this issue. Please reopen if needed.
