### ISSUE TITLE
HomeAssistant ERROR message

### ISSUE THREAD

**Issue by mbolo01** [giachello/beoplay#6]
Hi,

Please note the following error message :

2021-05-24 13:10:55 ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'beoplay'. As of 
Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'beoplay' 

Kind regards.

**Comment by giachello** [comment]
I fixed in the latest code. Please re-install the manifest.json file.

**Comment by mbolo01** [comment]
Thanks, sorry I should have read the code repository before raising an issue.
