### ISSUE TITLE
Add as device

### ISSUE THREAD

**Issue by KimCarlsen** [giachello/beoplay#7]
Featurerequest: it would be nice if the TV's and speakers was added as devices, so it was possible to do automations, based on device state etc.
e.g. i have some speakers that are on a controlled power outlet for energy saving. An automation could be to switch them on, when TV is powered on

**Comment by giachello** [comment]
Hi there, beoplay should support TVs and Speakers. Can you send me details of your setup?
BTW the B&O speakers are so power efficient that you should just leave them plugged in.

**Comment by KimCarlsen** [comment]
HI. 
I have a BV11, with speakers, setup box and game consoles connected. They are all connected to a separate power outlet controlled by HA. That I would like to turn on/off depending whether the BV11 is on/off

**Comment by giachello** [comment]
This should be now possible using entity state.

**Comment by KimCarlsen** [comment]
Thanks it works perfectly
